### ISSUE TITLE
Edit and Delete objects

### ISSUE THREAD

**Issue by aburka** [aburka/ohlinger#21]
- Art, events, and tattoos all need to be editable and deletable (with a 'are you sure' notification)
- I'd like for these to be available on the 'show' views, except for the events, that don't have a show view; those can be in the events/index view. 
  - I wrote a show/hide for the edit form, but it currently shows all of the forms on the page (wow helpful)
- Admin should be the only one who can edit and delete

**Comment by jacobthemyth** [comment]
- [x] Dates on events should show in edit form
- [x] Create a component for uploading an image
- [x] Events editable
- [x] Events deletable
- [x] Art editable
- [x] Art deletable
- [x] Store editable
- [x] Store deletable
- [x] Tattoos editable
- [x] Tattoos deletable
- [ ] Only admin can edit and delete
